package yyp

// project versions
const RES_VERSION = "1.7"
const AUDIO_GROUP_VERSION = "1.3"
const TEXTURE_GROUP_VERSION = "1.3"

// resource versions
const ANIMCURVE_VERSION = "1.2"
const ANIMCURVECHAN_VERSION = "1.0"
const EXT_VERSION = "1.2"
const FONT_VERSION = "1.0"
const NOTE_VERSION = "1.1"
const OBJ_VERSINON = "1.0"
const OBJEVENT_VERSION = "1.0"
const PARTICLE_VERSION = "1.0"
const PARTICLEEMIT_VERSION = "1.0"
const PATH_VERSION = "1.0"
const ROOM_VERSION = "1.0"
const SCRIPT_VERSION = "1.0"
const SEQ_VERSION = "1.4"
const SEQEVENT_VERSION = "1.0"
const SEQMOMENT_VERSION = "1.0"
const SHADER_VERSION = "1.0"
const SOUND_VERSION = "1.0"
const SPRITE_VERSION = "1.0"
const SPRITEFRAME_VERSION = "1.1"
const SPRITELAYER_VERSION = "1.0"
const SPRITETRACK_VERSION = "1.0"
const TILESET_VERSION = "1.0"
const TIMELINE_VERSION = "1.0"

// resource directories
const ANIMCURVE_DIR = "animcurves"
const EXT_DIR = "extensions"
const FONT_DIR = "fonts"
const NOTE_DIR = "notes"
const OBJ_DIR = "objects"
const PARTICLE_DIR = "particles"
const PATH_DIR = "paths"
const ROOM_DIR = "rooms"
const SCRIPT_DIR = "scripts"
const SEQ_DIR = "sequences"
const SHADER_DIR = "shaders"
const SOUND_DIR = "sounds"
const SPRITE_DIR = "sprites"
const TILESET_DIR = "tilesets"
const TIMELINE_DIR = "timelines"

// project file extensions
const EXT_PROJ = ".yyp"
const EXT_ORDER = ".resource_order"
const EXT_RESOURCE = ".yy"
const EXT_SCRIPT = ".gml"
const EXT_SHADER_VERTEX = ".vsh"
const EXT_SHADER_FRAGMENT = ".fsh"

// project options directories
const OPT = "options"
const OPT_ANDROID = "android"
const OPT_EXT = "extensions"
const OPT_HTML = "html5"
const OPT_IOS = "ios"
const OPT_LINUX = "linux"
const OPT_MAC = "mac"
const OPT_MAIN = "main"
const OPT_OPERAGX = "operagx"
const OPT_TV = "tvos"
const OPT_WINDOWS = "windows"

// resource types
const RESTYPE_PROJ = "GMProject"
const RESTYPE_AUDIOGROUP = "GMAudioGroup"
const RESTYPE_TEXTUREGROUP = "GMTextureGroup"
